# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sf/v4/geometry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sf/v4/geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sf/v4/geometry.proto\x12\x05sf.v4\x1a\x1cgoogle/protobuf/struct.proto\"\x13\n\x03\x43rs\x12\x0c\n\x04srid\x18\x01 \x01(\r\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\")\n\x05Point\x12 \n\x05\x63oord\x18\x01 \x01(\x0b\x32\x11.sf.v4.Coordinate\"*\n\nMultiPoint\x12\x1c\n\x06points\x18\x01 \x03(\x0b\x32\x0c.sf.v4.Point\"*\n\nLineString\x12\x1c\n\x06points\x18\x01 \x03(\x0b\x32\x0c.sf.v4.Point\":\n\x0fMultiLineString\x12\'\n\x0cline_strings\x18\x01 \x03(\x0b\x32\x11.sf.v4.LineString\"/\n\nLinearRing\x12!\n\x06\x63oords\x18\x01 \x03(\x0b\x32\x11.sf.v4.Coordinate\"+\n\x07Polygon\x12 \n\x05rings\x18\x01 \x03(\x0b\x32\x11.sf.v4.LinearRing\"0\n\x0cMultiPolygon\x12 \n\x08polygons\x18\x01 \x03(\x0b\x32\x0e.sf.v4.Polygon\"\xa0\x02\n\x08Geometry\x12\x17\n\x03\x63rs\x18\x01 \x01(\x0b\x32\n.sf.v4.Crs\x12\x1d\n\x05point\x18\n \x01(\x0b\x32\x0c.sf.v4.PointH\x00\x12(\n\x0bline_string\x18\x0b \x01(\x0b\x32\x11.sf.v4.LineStringH\x00\x12!\n\x07polygon\x18\x0c \x01(\x0b\x32\x0e.sf.v4.PolygonH\x00\x12+\n\x0cmultipolygon\x18\r \x01(\x0b\x32\x13.sf.v4.MultiPolygonH\x00\x12\x31\n\x0fmultilinestring\x18\x0e \x01(\x0b\x32\x16.sf.v4.MultiLineStringH\x00\x12\'\n\nmultipoint\x18\x0f \x01(\x0b\x32\x11.sf.v4.MultiPointH\x00\x42\x06\n\x04geom\"\x9b\x01\n\x07\x46\x65\x61ture\x12!\n\x08geometry\x18\x01 \x01(\x0b\x32\x0f.sf.v4.Geometry\x12+\n\nproperties\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0c\n\x04\x62\x62ox\x18\x04 \x03(\x01\x12&\n\x05\x65xtra\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x92\x01\n\x11\x46\x65\x61tureCollection\x12 \n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x0e.sf.v4.Feature\x12\x0c\n\x04\x62\x62ox\x18\x02 \x03(\x01\x12&\n\x05\x65xtra\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x17\n\x03\x63rs\x18\x05 \x01(\x0b\x32\n.sf.v4.Crsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.v4.geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CRS']._serialized_start=61
  _globals['_CRS']._serialized_end=80
  _globals['_COORDINATE']._serialized_start=82
  _globals['_COORDINATE']._serialized_end=116
  _globals['_POINT']._serialized_start=118
  _globals['_POINT']._serialized_end=159
  _globals['_MULTIPOINT']._serialized_start=161
  _globals['_MULTIPOINT']._serialized_end=203
  _globals['_LINESTRING']._serialized_start=205
  _globals['_LINESTRING']._serialized_end=247
  _globals['_MULTILINESTRING']._serialized_start=249
  _globals['_MULTILINESTRING']._serialized_end=307
  _globals['_LINEARRING']._serialized_start=309
  _globals['_LINEARRING']._serialized_end=356
  _globals['_POLYGON']._serialized_start=358
  _globals['_POLYGON']._serialized_end=401
  _globals['_MULTIPOLYGON']._serialized_start=403
  _globals['_MULTIPOLYGON']._serialized_end=451
  _globals['_GEOMETRY']._serialized_start=454
  _globals['_GEOMETRY']._serialized_end=742
  _globals['_FEATURE']._serialized_start=745
  _globals['_FEATURE']._serialized_end=900
  _globals['_FEATURECOLLECTION']._serialized_start=903
  _globals['_FEATURECOLLECTION']._serialized_end=1049
# @@protoc_insertion_point(module_scope)
